/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.ActivityType = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Enum class ActivityType.
   * @enum {String}
   * @readonly
   */
  var exports = {
    /**
     * value: "AlpineSki"
     * @const
     */
    alpineSki: "AlpineSki",

    /**
     * value: "BackcountrySki"
     * @const
     */
    backcountrySki: "BackcountrySki",

    /**
     * value: "Canoeing"
     * @const
     */
    canoeing: "Canoeing",

    /**
     * value: "Crossfit"
     * @const
     */
    crossfit: "Crossfit",

    /**
     * value: "EBikeRide"
     * @const
     */
    eBikeRide: "EBikeRide",

    /**
     * value: "Elliptical"
     * @const
     */
    elliptical: "Elliptical",

    /**
     * value: "Golf"
     * @const
     */
    golf: "Golf",

    /**
     * value: "Handcycle"
     * @const
     */
    handcycle: "Handcycle",

    /**
     * value: "Hike"
     * @const
     */
    hike: "Hike",

    /**
     * value: "IceSkate"
     * @const
     */
    iceSkate: "IceSkate",

    /**
     * value: "InlineSkate"
     * @const
     */
    inlineSkate: "InlineSkate",

    /**
     * value: "Kayaking"
     * @const
     */
    kayaking: "Kayaking",

    /**
     * value: "Kitesurf"
     * @const
     */
    kitesurf: "Kitesurf",

    /**
     * value: "NordicSki"
     * @const
     */
    nordicSki: "NordicSki",

    /**
     * value: "Ride"
     * @const
     */
    ride: "Ride",

    /**
     * value: "RockClimbing"
     * @const
     */
    rockClimbing: "RockClimbing",

    /**
     * value: "RollerSki"
     * @const
     */
    rollerSki: "RollerSki",

    /**
     * value: "Rowing"
     * @const
     */
    rowing: "Rowing",

    /**
     * value: "Run"
     * @const
     */
    run: "Run",

    /**
     * value: "Sail"
     * @const
     */
    sail: "Sail",

    /**
     * value: "Skateboard"
     * @const
     */
    skateboard: "Skateboard",

    /**
     * value: "Snowboard"
     * @const
     */
    snowboard: "Snowboard",

    /**
     * value: "Snowshoe"
     * @const
     */
    snowshoe: "Snowshoe",

    /**
     * value: "Soccer"
     * @const
     */
    soccer: "Soccer",

    /**
     * value: "StairStepper"
     * @const
     */
    stairStepper: "StairStepper",

    /**
     * value: "StandUpPaddling"
     * @const
     */
    standUpPaddling: "StandUpPaddling",

    /**
     * value: "Surfing"
     * @const
     */
    surfing: "Surfing",

    /**
     * value: "Swim"
     * @const
     */
    swim: "Swim",

    /**
     * value: "Velomobile"
     * @const
     */
    velomobile: "Velomobile",

    /**
     * value: "VirtualRide"
     * @const
     */
    virtualRide: "VirtualRide",

    /**
     * value: "VirtualRun"
     * @const
     */
    virtualRun: "VirtualRun",

    /**
     * value: "Walk"
     * @const
     */
    walk: "Walk",

    /**
     * value: "WeightTraining"
     * @const
     */
    weightTraining: "WeightTraining",

    /**
     * value: "Wheelchair"
     * @const
     */
    wheelchair: "Wheelchair",

    /**
     * value: "Windsurf"
     * @const
     */
    windsurf: "Windsurf",

    /**
     * value: "Workout"
     * @const
     */
    workout: "Workout",

    /**
     * value: "Yoga"
     * @const
     */
    yoga: "Yoga"
  };

  /**
   * Returns a <code>ActivityType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ActivityType} The enum <code>ActivityType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));
