/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ActivityType', function() {
      beforeEach(function() {
        instance = StravaApiV3.ActivityType;
      });

      it('should create an instance of ActivityType', function() {
        // TODO: update the code to test ActivityType
        expect(instance).to.be.a('object');
      });

      it('should have the property alpineSki', function() {
        expect(instance).to.have.property('alpineSki');
        expect(instance.alpineSki).to.be("AlpineSki");
      });

      it('should have the property backcountrySki', function() {
        expect(instance).to.have.property('backcountrySki');
        expect(instance.backcountrySki).to.be("BackcountrySki");
      });

      it('should have the property canoeing', function() {
        expect(instance).to.have.property('canoeing');
        expect(instance.canoeing).to.be("Canoeing");
      });

      it('should have the property crossfit', function() {
        expect(instance).to.have.property('crossfit');
        expect(instance.crossfit).to.be("Crossfit");
      });

      it('should have the property eBikeRide', function() {
        expect(instance).to.have.property('eBikeRide');
        expect(instance.eBikeRide).to.be("EBikeRide");
      });

      it('should have the property elliptical', function() {
        expect(instance).to.have.property('elliptical');
        expect(instance.elliptical).to.be("Elliptical");
      });

      it('should have the property golf', function() {
        expect(instance).to.have.property('golf');
        expect(instance.golf).to.be("Golf");
      });

      it('should have the property handcycle', function() {
        expect(instance).to.have.property('handcycle');
        expect(instance.handcycle).to.be("Handcycle");
      });

      it('should have the property hike', function() {
        expect(instance).to.have.property('hike');
        expect(instance.hike).to.be("Hike");
      });

      it('should have the property iceSkate', function() {
        expect(instance).to.have.property('iceSkate');
        expect(instance.iceSkate).to.be("IceSkate");
      });

      it('should have the property inlineSkate', function() {
        expect(instance).to.have.property('inlineSkate');
        expect(instance.inlineSkate).to.be("InlineSkate");
      });

      it('should have the property kayaking', function() {
        expect(instance).to.have.property('kayaking');
        expect(instance.kayaking).to.be("Kayaking");
      });

      it('should have the property kitesurf', function() {
        expect(instance).to.have.property('kitesurf');
        expect(instance.kitesurf).to.be("Kitesurf");
      });

      it('should have the property nordicSki', function() {
        expect(instance).to.have.property('nordicSki');
        expect(instance.nordicSki).to.be("NordicSki");
      });

      it('should have the property ride', function() {
        expect(instance).to.have.property('ride');
        expect(instance.ride).to.be("Ride");
      });

      it('should have the property rockClimbing', function() {
        expect(instance).to.have.property('rockClimbing');
        expect(instance.rockClimbing).to.be("RockClimbing");
      });

      it('should have the property rollerSki', function() {
        expect(instance).to.have.property('rollerSki');
        expect(instance.rollerSki).to.be("RollerSki");
      });

      it('should have the property rowing', function() {
        expect(instance).to.have.property('rowing');
        expect(instance.rowing).to.be("Rowing");
      });

      it('should have the property run', function() {
        expect(instance).to.have.property('run');
        expect(instance.run).to.be("Run");
      });

      it('should have the property sail', function() {
        expect(instance).to.have.property('sail');
        expect(instance.sail).to.be("Sail");
      });

      it('should have the property skateboard', function() {
        expect(instance).to.have.property('skateboard');
        expect(instance.skateboard).to.be("Skateboard");
      });

      it('should have the property snowboard', function() {
        expect(instance).to.have.property('snowboard');
        expect(instance.snowboard).to.be("Snowboard");
      });

      it('should have the property snowshoe', function() {
        expect(instance).to.have.property('snowshoe');
        expect(instance.snowshoe).to.be("Snowshoe");
      });

      it('should have the property soccer', function() {
        expect(instance).to.have.property('soccer');
        expect(instance.soccer).to.be("Soccer");
      });

      it('should have the property stairStepper', function() {
        expect(instance).to.have.property('stairStepper');
        expect(instance.stairStepper).to.be("StairStepper");
      });

      it('should have the property standUpPaddling', function() {
        expect(instance).to.have.property('standUpPaddling');
        expect(instance.standUpPaddling).to.be("StandUpPaddling");
      });

      it('should have the property surfing', function() {
        expect(instance).to.have.property('surfing');
        expect(instance.surfing).to.be("Surfing");
      });

      it('should have the property swim', function() {
        expect(instance).to.have.property('swim');
        expect(instance.swim).to.be("Swim");
      });

      it('should have the property velomobile', function() {
        expect(instance).to.have.property('velomobile');
        expect(instance.velomobile).to.be("Velomobile");
      });

      it('should have the property virtualRide', function() {
        expect(instance).to.have.property('virtualRide');
        expect(instance.virtualRide).to.be("VirtualRide");
      });

      it('should have the property virtualRun', function() {
        expect(instance).to.have.property('virtualRun');
        expect(instance.virtualRun).to.be("VirtualRun");
      });

      it('should have the property walk', function() {
        expect(instance).to.have.property('walk');
        expect(instance.walk).to.be("Walk");
      });

      it('should have the property weightTraining', function() {
        expect(instance).to.have.property('weightTraining');
        expect(instance.weightTraining).to.be("WeightTraining");
      });

      it('should have the property wheelchair', function() {
        expect(instance).to.have.property('wheelchair');
        expect(instance.wheelchair).to.be("Wheelchair");
      });

      it('should have the property windsurf', function() {
        expect(instance).to.have.property('windsurf');
        expect(instance.windsurf).to.be("Windsurf");
      });

      it('should have the property workout', function() {
        expect(instance).to.have.property('workout');
        expect(instance.workout).to.be("Workout");
      });

      it('should have the property yoga', function() {
        expect(instance).to.have.property('yoga');
        expect(instance.yoga).to.be("Yoga");
      });

    });
  });

}));
