/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DetailedAthlete', function() {
      beforeEach(function() {
        instance = new StravaApiV3.DetailedAthlete();
      });

      it('should create an instance of DetailedAthlete', function() {
        // TODO: update the code to test DetailedAthlete
        expect(instance).to.be.a(StravaApiV3.DetailedAthlete);
      });

      it('should have the property followerCount (base name: "follower_count")', function() {
        // TODO: update the code to test the property followerCount
        expect(instance).to.have.property('followerCount');
        // expect(instance.followerCount).to.be(expectedValueLiteral);
      });

      it('should have the property friendCount (base name: "friend_count")', function() {
        // TODO: update the code to test the property friendCount
        expect(instance).to.have.property('friendCount');
        // expect(instance.friendCount).to.be(expectedValueLiteral);
      });

      it('should have the property measurementPreference (base name: "measurement_preference")', function() {
        // TODO: update the code to test the property measurementPreference
        expect(instance).to.have.property('measurementPreference');
        // expect(instance.measurementPreference).to.be(expectedValueLiteral);
      });

      it('should have the property ftp (base name: "ftp")', function() {
        // TODO: update the code to test the property ftp
        expect(instance).to.have.property('ftp');
        // expect(instance.ftp).to.be(expectedValueLiteral);
      });

      it('should have the property weight (base name: "weight")', function() {
        // TODO: update the code to test the property weight
        expect(instance).to.have.property('weight');
        // expect(instance.weight).to.be(expectedValueLiteral);
      });

      it('should have the property clubs (base name: "clubs")', function() {
        // TODO: update the code to test the property clubs
        expect(instance).to.have.property('clubs');
        // expect(instance.clubs).to.be(expectedValueLiteral);
      });

      it('should have the property bikes (base name: "bikes")', function() {
        // TODO: update the code to test the property bikes
        expect(instance).to.have.property('bikes');
        // expect(instance.bikes).to.be(expectedValueLiteral);
      });

      it('should have the property shoes (base name: "shoes")', function() {
        // TODO: update the code to test the property shoes
        expect(instance).to.have.property('shoes');
        // expect(instance.shoes).to.be(expectedValueLiteral);
      });

    });
  });

}));
