/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PhotosSummaryPrimary', function() {
      beforeEach(function() {
        instance = new StravaApiV3.PhotosSummaryPrimary();
      });

      it('should create an instance of PhotosSummaryPrimary', function() {
        // TODO: update the code to test PhotosSummaryPrimary
        expect(instance).to.be.a(StravaApiV3.PhotosSummaryPrimary);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property source (base name: "source")', function() {
        // TODO: update the code to test the property source
        expect(instance).to.have.property('source');
        // expect(instance.source).to.be(expectedValueLiteral);
      });

      it('should have the property uniqueId (base name: "unique_id")', function() {
        // TODO: update the code to test the property uniqueId
        expect(instance).to.have.property('uniqueId');
        // expect(instance.uniqueId).to.be(expectedValueLiteral);
      });

      it('should have the property urls (base name: "urls")', function() {
        // TODO: update the code to test the property urls
        expect(instance).to.have.property('urls');
        // expect(instance.urls).to.be(expectedValueLiteral);
      });

    });
  });

}));
