/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.RoutesApi();
  });

  describe('(package)', function() {
    describe('RoutesApi', function() {
      describe('getRouteAsGPX', function() {
        it('should call getRouteAsGPX successfully', function(done) {
          // TODO: uncomment, update parameter values for getRouteAsGPX call
          /*
          var id = 789;

          instance.getRouteAsGPX(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getRouteAsTCX', function() {
        it('should call getRouteAsTCX successfully', function(done) {
          // TODO: uncomment, update parameter values for getRouteAsTCX call
          /*
          var id = 789;

          instance.getRouteAsTCX(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getRouteById', function() {
        it('should call getRouteById successfully', function(done) {
          // TODO: uncomment, update parameter values for getRouteById call and complete the assertions
          /*
          var id = 789;

          instance.getRouteById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(StravaApiV3.Route);
            expect(data.athlete).to.be.a(StravaApiV3.SummaryAthlete);
                  expect(data.athlete.id).to.be.a('number');
              expect(data.athlete.id).to.be("0");
              expect(data.athlete.resourceState).to.be.a('number');
              expect(data.athlete.resourceState).to.be(0);
              expect(data.athlete.firstname).to.be.a('string');
              expect(data.athlete.firstname).to.be("");
              expect(data.athlete.lastname).to.be.a('string');
              expect(data.athlete.lastname).to.be("");
              expect(data.athlete.profileMedium).to.be.a('string');
              expect(data.athlete.profileMedium).to.be("");
              expect(data.athlete.profile).to.be.a('string');
              expect(data.athlete.profile).to.be("");
              expect(data.athlete.city).to.be.a('string');
              expect(data.athlete.city).to.be("");
              expect(data.athlete.state).to.be.a('string');
              expect(data.athlete.state).to.be("");
              expect(data.athlete.country).to.be.a('string');
              expect(data.athlete.country).to.be("");
              expect(data.athlete.sex).to.be.a('string');
              expect(data.athlete.sex).to.be("M");
              expect(data.athlete.premium).to.be.a('boolean');
              expect(data.athlete.premium).to.be(false);
              expect(data.athlete.summit).to.be.a('boolean');
              expect(data.athlete.summit).to.be(false);
              expect(data.athlete.createdAt).to.be.a(Date);
              expect(data.athlete.createdAt).to.be(new Date());
              expect(data.athlete.updatedAt).to.be.a(Date);
              expect(data.athlete.updatedAt).to.be(new Date());
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.distance).to.be.a('number');
            expect(data.distance).to.be(0.0);
            expect(data.elevationGain).to.be.a('number');
            expect(data.elevationGain).to.be(0.0);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.idStr).to.be.a('string');
            expect(data.idStr).to.be("");
            expect(data.map).to.be.a(StravaApiV3.PolylineMap);
                  expect(data.map.id).to.be.a('string');
              expect(data.map.id).to.be("");
              expect(data.map.polyline).to.be.a('string');
              expect(data.map.polyline).to.be("");
              expect(data.map.summaryPolyline).to.be.a('string');
              expect(data.map.summaryPolyline).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data._private).to.be.a('boolean');
            expect(data._private).to.be(false);
            expect(data.starred).to.be.a('boolean');
            expect(data.starred).to.be(false);
            expect(data.timestamp).to.be.a('number');
            expect(data.timestamp).to.be(0);
            expect(data.type).to.be.a('number');
            expect(data.type).to.be(0);
            expect(data.subType).to.be.a('number');
            expect(data.subType).to.be(0);
            {
              let dataCtr = data.segments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(StravaApiV3.SummarySegment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.activityType).to.be.a('string');
                expect(data.activityType).to.be("Ride");
                expect(data.distance).to.be.a('number');
                expect(data.distance).to.be(0.0);
                expect(data.averageGrade).to.be.a('number');
                expect(data.averageGrade).to.be(0.0);
                expect(data.maximumGrade).to.be.a('number');
                expect(data.maximumGrade).to.be(0.0);
                expect(data.elevationHigh).to.be.a('number');
                expect(data.elevationHigh).to.be(0.0);
                expect(data.elevationLow).to.be.a('number');
                expect(data.elevationLow).to.be(0.0);
                expect(data.startLatlng).to.be.a(StravaApiV3.LatLng);
                    expect(data.endLatlng).to.be.a(StravaApiV3.LatLng);
                    expect(data.climbCategory).to.be.a('number');
                expect(data.climbCategory).to.be(0);
                expect(data.city).to.be.a('string');
                expect(data.city).to.be("");
                expect(data.state).to.be.a('string');
                expect(data.state).to.be("");
                expect(data.country).to.be.a('string');
                expect(data.country).to.be("");
                expect(data._private).to.be.a('boolean');
                expect(data._private).to.be(false);
                expect(data.athletePrEffort).to.be.a(StravaApiV3.SummarySegmentEffort);
                      expect(data.athletePrEffort.id).to.be.a('number');
                  expect(data.athletePrEffort.id).to.be("0");
                  expect(data.athletePrEffort.activityId).to.be.a('number');
                  expect(data.athletePrEffort.activityId).to.be("0");
                  expect(data.athletePrEffort.elapsedTime).to.be.a('number');
                  expect(data.athletePrEffort.elapsedTime).to.be(0);
                  expect(data.athletePrEffort.startDate).to.be.a(Date);
                  expect(data.athletePrEffort.startDate).to.be(new Date());
                  expect(data.athletePrEffort.startDateLocal).to.be.a(Date);
                  expect(data.athletePrEffort.startDateLocal).to.be(new Date());
                  expect(data.athletePrEffort.distance).to.be.a('number');
                  expect(data.athletePrEffort.distance).to.be(0.0);
                  expect(data.athletePrEffort.isKom).to.be.a('boolean');
                  expect(data.athletePrEffort.isKom).to.be(false);
                expect(data.athleteSegmentStats).to.be.a(StravaApiV3.SummaryPRSegmentEffort);
                      expect(data.athleteSegmentStats.prActivityId).to.be.a('number');
                  expect(data.athleteSegmentStats.prActivityId).to.be("0");
                  expect(data.athleteSegmentStats.prElapsedTime).to.be.a('number');
                  expect(data.athleteSegmentStats.prElapsedTime).to.be(0);
                  expect(data.athleteSegmentStats.prDate).to.be.a(Date);
                  expect(data.athleteSegmentStats.prDate).to.be(new Date());
                  expect(data.athleteSegmentStats.effortCount).to.be.a('number');
                  expect(data.athleteSegmentStats.effortCount).to.be(0);

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getRoutesByAthleteId', function() {
        it('should call getRoutesByAthleteId successfully', function(done) {
          // TODO: uncomment, update parameter values for getRoutesByAthleteId call and complete the assertions
          /*
          var id = 789;
          var opts = {};
          opts.page = 56;
          opts.perPage = 30;

          instance.getRoutesByAthleteId(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(StravaApiV3.Route);
              expect(data.athlete).to.be.a(StravaApiV3.SummaryAthlete);
                    expect(data.athlete.id).to.be.a('number');
                expect(data.athlete.id).to.be("0");
                expect(data.athlete.resourceState).to.be.a('number');
                expect(data.athlete.resourceState).to.be(0);
                expect(data.athlete.firstname).to.be.a('string');
                expect(data.athlete.firstname).to.be("");
                expect(data.athlete.lastname).to.be.a('string');
                expect(data.athlete.lastname).to.be("");
                expect(data.athlete.profileMedium).to.be.a('string');
                expect(data.athlete.profileMedium).to.be("");
                expect(data.athlete.profile).to.be.a('string');
                expect(data.athlete.profile).to.be("");
                expect(data.athlete.city).to.be.a('string');
                expect(data.athlete.city).to.be("");
                expect(data.athlete.state).to.be.a('string');
                expect(data.athlete.state).to.be("");
                expect(data.athlete.country).to.be.a('string');
                expect(data.athlete.country).to.be("");
                expect(data.athlete.sex).to.be.a('string');
                expect(data.athlete.sex).to.be("M");
                expect(data.athlete.premium).to.be.a('boolean');
                expect(data.athlete.premium).to.be(false);
                expect(data.athlete.summit).to.be.a('boolean');
                expect(data.athlete.summit).to.be(false);
                expect(data.athlete.createdAt).to.be.a(Date);
                expect(data.athlete.createdAt).to.be(new Date());
                expect(data.athlete.updatedAt).to.be.a(Date);
                expect(data.athlete.updatedAt).to.be(new Date());
              expect(data.description).to.be.a('string');
              expect(data.description).to.be("");
              expect(data.distance).to.be.a('number');
              expect(data.distance).to.be(0.0);
              expect(data.elevationGain).to.be.a('number');
              expect(data.elevationGain).to.be(0.0);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.idStr).to.be.a('string');
              expect(data.idStr).to.be("");
              expect(data.map).to.be.a(StravaApiV3.PolylineMap);
                    expect(data.map.id).to.be.a('string');
                expect(data.map.id).to.be("");
                expect(data.map.polyline).to.be.a('string');
                expect(data.map.polyline).to.be("");
                expect(data.map.summaryPolyline).to.be.a('string');
                expect(data.map.summaryPolyline).to.be("");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data._private).to.be.a('boolean');
              expect(data._private).to.be(false);
              expect(data.starred).to.be.a('boolean');
              expect(data.starred).to.be(false);
              expect(data.timestamp).to.be.a('number');
              expect(data.timestamp).to.be(0);
              expect(data.type).to.be.a('number');
              expect(data.type).to.be(0);
              expect(data.subType).to.be.a('number');
              expect(data.subType).to.be(0);
              {
                let dataCtr = data.segments;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(StravaApiV3.SummarySegment);
                  expect(data.id).to.be.a('number');
                  expect(data.id).to.be("0");
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("");
                  expect(data.activityType).to.be.a('string');
                  expect(data.activityType).to.be("Ride");
                  expect(data.distance).to.be.a('number');
                  expect(data.distance).to.be(0.0);
                  expect(data.averageGrade).to.be.a('number');
                  expect(data.averageGrade).to.be(0.0);
                  expect(data.maximumGrade).to.be.a('number');
                  expect(data.maximumGrade).to.be(0.0);
                  expect(data.elevationHigh).to.be.a('number');
                  expect(data.elevationHigh).to.be(0.0);
                  expect(data.elevationLow).to.be.a('number');
                  expect(data.elevationLow).to.be(0.0);
                  expect(data.startLatlng).to.be.a(StravaApiV3.LatLng);
                      expect(data.endLatlng).to.be.a(StravaApiV3.LatLng);
                      expect(data.climbCategory).to.be.a('number');
                  expect(data.climbCategory).to.be(0);
                  expect(data.city).to.be.a('string');
                  expect(data.city).to.be("");
                  expect(data.state).to.be.a('string');
                  expect(data.state).to.be("");
                  expect(data.country).to.be.a('string');
                  expect(data.country).to.be("");
                  expect(data._private).to.be.a('boolean');
                  expect(data._private).to.be(false);
                  expect(data.athletePrEffort).to.be.a(StravaApiV3.SummarySegmentEffort);
                        expect(data.athletePrEffort.id).to.be.a('number');
                    expect(data.athletePrEffort.id).to.be("0");
                    expect(data.athletePrEffort.activityId).to.be.a('number');
                    expect(data.athletePrEffort.activityId).to.be("0");
                    expect(data.athletePrEffort.elapsedTime).to.be.a('number');
                    expect(data.athletePrEffort.elapsedTime).to.be(0);
                    expect(data.athletePrEffort.startDate).to.be.a(Date);
                    expect(data.athletePrEffort.startDate).to.be(new Date());
                    expect(data.athletePrEffort.startDateLocal).to.be.a(Date);
                    expect(data.athletePrEffort.startDateLocal).to.be(new Date());
                    expect(data.athletePrEffort.distance).to.be.a('number');
                    expect(data.athletePrEffort.distance).to.be(0.0);
                    expect(data.athletePrEffort.isKom).to.be.a('boolean');
                    expect(data.athletePrEffort.isKom).to.be(false);
                  expect(data.athleteSegmentStats).to.be.a(StravaApiV3.SummaryPRSegmentEffort);
                        expect(data.athleteSegmentStats.prActivityId).to.be.a('number');
                    expect(data.athleteSegmentStats.prActivityId).to.be("0");
                    expect(data.athleteSegmentStats.prElapsedTime).to.be.a('number');
                    expect(data.athleteSegmentStats.prElapsedTime).to.be(0);
                    expect(data.athleteSegmentStats.prDate).to.be.a(Date);
                    expect(data.athleteSegmentStats.prDate).to.be(new Date());
                    expect(data.athleteSegmentStats.effortCount).to.be.a('number');
                    expect(data.athleteSegmentStats.effortCount).to.be(0);
  
                        }
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
