/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.UploadsApi();
  });

  describe('(package)', function() {
    describe('UploadsApi', function() {
      describe('createUpload', function() {
        it('should call createUpload successfully', function(done) {
          // TODO: uncomment, update parameter values for createUpload call and complete the assertions
          /*
          var opts = {};
          opts.file = "/path/to/file.txt";
          opts.name = "name_example";
          opts.description = "description_example";
          opts.trainer = "trainer_example";
          opts.commute = "commute_example";
          opts.dataType = "dataType_example";
          opts.externalId = "externalId_example";

          instance.createUpload(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(StravaApiV3.Upload);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.idStr).to.be.a('string');
            expect(data.idStr).to.be("");
            expect(data.externalId).to.be.a('string');
            expect(data.externalId).to.be("");
            expect(data.error).to.be.a('string');
            expect(data.error).to.be("");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.activityId).to.be.a('number');
            expect(data.activityId).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUploadById', function() {
        it('should call getUploadById successfully', function(done) {
          // TODO: uncomment, update parameter values for getUploadById call and complete the assertions
          /*
          var uploadId = 789;

          instance.getUploadById(uploadId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(StravaApiV3.Upload);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.idStr).to.be.a('string');
            expect(data.idStr).to.be("");
            expect(data.externalId).to.be.a('string');
            expect(data.externalId).to.be("");
            expect(data.error).to.be.a('string');
            expect(data.error).to.be("");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.activityId).to.be.a('number');
            expect(data.activityId).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
